version: 2
jobs:
  build:
    docker:
      - image: vihervas/circleci-golang-node:1.9.2-6.11.2
    working_directory: /go/src/github.com/mmmsasaki/simple-go-server
    steps:
      - checkout
      - run: go version     # 1.9.2
      - run: node --version # v6.11.2
      - run: npm --version  # 3.10.10
      - run: sudo npm install -g dredd
      - run: go build
      - run: go get github.com/snikch/goodman/cmd/goodman
      - run: go build -o hooks ./test/hooks.go
      - run: dredd
